# version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
       db:
         condition: service_healthy 
    environment:
      DB_HOST: "db"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_PORT: 3306
      DB_NAME: "file_share"
    networks:
      - go-network
    
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: file_share
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - go-network
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]  
      interval: 10s  
      retries: 5  
      start_period: 20s  
    
networks:
  go-network:
    driver: bridge

volumes:
   db_data:
    
