FROM golang:1.23.4-alpine3.20 AS builder

WORKDIR /app 

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o cmd/main cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/cmd/main .

EXPOSE 8080

CMD ["./cmd/main"]